name: Deploy to Azure App Services

on:
  push:
    branches:
      - airlines

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Upload for Deployment
        uses: actions/upload-artifact@v3
        with:
          name: SpringSOAP
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: SpringSOAP
          path: .

      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'travelbroker'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
